### ISSUE TITLE
Access to 300k and 600k

### ISSUE THREAD

**Issue by eitiyamamoto** [ruizhang-ai/EA_for_KG#5]
Hi!

I tried to access the file to the large datasets (300k and 600k) using the links in the read me, but it was broken. Can you fix the link?

Thank you very much!

**Comment by ethanmock** [comment]
Hi, we have updated the download link where the large dataset can be downloaded at Baidu Drive: https://pan.baidu.com/s/1t938_11rofeMIYHwqqXP4Q?pwd=AtAl

**Comment by eitiyamamoto** [comment]
Thank you very much!
It will help me a lot during my research!
